[phases.setup]
nixPkgs = ['python3', 'gcc']

[phases.install]
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[start]
cmd = '. /opt/venv/bin/activate && gunicorn main:app --bind 0.0.0.0:${PORT:-8080} --timeout 300 --workers 1 --threads 4 --worker-class gthread --log-level debug'
